@startuml
'https://plantuml.com/class-diagram
class Computer{
    String CPU, ram, screen, storage;
    #Computer(Builder b);
}
class Builder{
    String CPU, ram, screen, storage;
    +Builder buildCPU(String CPU);
    +Builder buildRAM(String RAM);
    +Builder buildscreen(String screen);
    +Builder builstorage(String storage);
    +Computer build();
}

Builder ..> Computer

@enduml